/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const axios: typeof import('axios').default
  const dayjs: typeof import('dayjs').default
  const storeToRefs: typeof import('pinia').storeToRefs
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly axios: UnwrapRef<typeof import('axios')['default']>
    readonly dayjs: UnwrapRef<typeof import('dayjs')['default']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
  }
}